import React, { useState } from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Switch, Alert } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Ionicons } from "@expo/vector-icons";
import COLORS from "../../constants/colors";
import { useAuth } from "../../hooks/useAuth";

export default function ProfileScreen({navigation}) {
  const {profile,logout}=useAuth();const [prefs,setPrefs]=useState({temp:true,hum:true,gas:true,offline:true,shipment:false});
  async function handleLogout(){try{await logout();navigation.getParent()?.replace("Login")}catch(e){Alert.alert("Logout failed",e.message)}}
  return <View style={styles.screen}><View style={styles.top}><Text style={styles.title}>Profile</Text></View><ScrollView contentContainerStyle={styles.content}><View style={styles.head}><LinearGradient colors={[COLORS.green,COLORS.blue]} style={styles.avatar}><Text style={styles.avatarText}>{initials(profile?.name||profile?.email)}</Text></LinearGradient><Text style={styles.name}>{profile?.name||profile?.email||"AgriTrace User"}</Text><Text style={styles.muted}>{profile?.role||"USER"}</Text><Text style={styles.role}>{profile?.organisation||"AgriTrace Network"}</Text></View><Section><Item icon="mail-outline" text={profile?.email||"—"}/><Item icon="call-outline" text={profile?.phone||"Phone not added"}/><Item icon="business-outline" text={profile?.organisation||"Organisation not added"} last/></Section><Label text="Notification Settings"/><Section>{Object.entries({temp:"Temperature Alerts",hum:"Humidity Alerts",gas:"Gas Alerts",offline:"Device Offline Alerts",shipment:"Shipment Updates"}).map(([k,l],i)=><View key={k} style={[styles.toggle,i===4&&{borderBottomWidth:0}]}><Text style={styles.itemText}>{l}</Text><Switch value={prefs[k]} onValueChange={()=>setPrefs(p=>({...p,[k]:!p[k]}))} trackColor={{false:COLORS.border,true:COLORS.emerald}} thumbColor={COLORS.white}/></View>)}</Section><TouchableOpacity style={styles.logout} onPress={()=>Alert.alert("Log out of AgriTrace?","You'll need to sign in again.",[{text:"Cancel",style:"cancel"},{text:"Log Out",style:"destructive",onPress:handleLogout}])}><Ionicons name="log-out-outline" size={19} color={COLORS.critical}/><Text style={styles.logoutText}>Logout</Text></TouchableOpacity></ScrollView></View>
}
const initials=s=>(s||"AT").split(/[\s@]/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("");function Label({text}){return <Text style={styles.label}>{text}</Text>}function Section({children}){return <View style={styles.section}>{children}</View>}function Item({icon,text,last}){return <View style={[styles.item,last&&{borderBottomWidth:0}]}><Ionicons name={icon} size={19} color={COLORS.green}/><Text style={styles.itemText}>{text}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.background},top:{height:58,justifyContent:"center",paddingHorizontal:18,backgroundColor:COLORS.white,borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontFamily:"Manrope_800ExtraBold",fontSize:16,color:COLORS.text},content:{padding:18,paddingBottom:105},head:{alignItems:"center",paddingVertical:14,marginBottom:8},avatar:{width:74,height:74,borderRadius:37,alignItems:"center",justifyContent:"center",marginBottom:8},avatarText:{fontFamily:"Manrope_800ExtraBold",fontSize:24,color:COLORS.white},name:{fontFamily:"Manrope_800ExtraBold",fontSize:17,color:COLORS.text},muted:{fontFamily:"Inter_400Regular",fontSize:12.5,color:COLORS.muted,marginTop:2},role:{fontFamily:"Inter_700Bold",fontSize:11,color:COLORS.forest,backgroundColor:COLORS.greenLight,paddingHorizontal:10,paddingVertical:4,borderRadius:99,marginTop:7},section:{backgroundColor:COLORS.white,borderWidth:1,borderColor:COLORS.border,borderRadius:16,overflow:"hidden",marginBottom:18},item:{flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:16,paddingVertical:14,borderBottomWidth:1,borderBottomColor:COLORS.border},itemText:{flex:1,fontFamily:"Inter_600SemiBold",fontSize:13,color:COLORS.text},toggle:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16,paddingVertical:9,borderBottomWidth:1,borderBottomColor:COLORS.border},label:{fontFamily:"Manrope_800ExtraBold",fontSize:13.5,color:COLORS.text,marginBottom:10},logout:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8,backgroundColor:COLORS.criticalLight,borderRadius:12,paddingVertical:14},logoutText:{fontFamily:"Inter_700Bold",fontSize:13,color:COLORS.critical}})
