import React, { useEffect, useState } from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import COLORS from "../../constants/colors";
import TopBar from "../../components/common/TopBar";
import Loader from "../../components/common/Loader";
import { getShipment } from "../../api/shipmentApi";
import { getTimeline } from "../../api/traceabilityApi";
import { verifyShipmentIntegrity } from "../../api/integrityApi";

export default function TraceabilityScreen({navigation,route}) {
  const id=route.params?.shipmentId;const [shipment,setShipment]=useState(null),[timeline,setTimeline]=useState([]),[integrity,setIntegrity]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null);
  useEffect(()=>{Promise.all([getShipment(id),getTimeline(id),verifyShipmentIntegrity(id)]).then(([s,t,i])=>{setShipment(s);setTimeline(t||[]);setIntegrity(i)}).catch(setError).finally(()=>setLoading(false))},[id]);
  if(loading)return <Loader text="Loading traceability..."/>;
  return <View style={styles.screen}><TopBar title="Farm-to-Fork Journey" navigation={navigation}/><ScrollView contentContainerStyle={styles.content}>{error?<Text style={styles.err}>{error.message}</Text>:null}<Text style={styles.ship}>{shipment?.shipmentId||id}</Text><Text style={styles.product}>{shipment?.product||shipment?.productName||"Shipment"}</Text><View style={styles.timeline}>{timeline.map((st,i)=><View key={st.eventId||`${st.type}-${i}`} style={styles.item}><View style={styles.markerCol}><View style={[styles.marker,i<timeline.length-1&&styles.completed]}><Ionicons name={i<timeline.length-1?"checkmark":"car-outline"} size={12} color={COLORS.white}/></View>{i<timeline.length-1&&<View style={styles.line}/>}</View><View style={{flex:1,paddingBottom:22}}><Text style={styles.tTitle}>{String(st.type||"EVENT").replace(/_/g," ")}</Text><Text style={styles.tSub}>{metadataText(st.metadata)}</Text><Text style={styles.tTime}>{formatDate(st.timestamp||st.createdAt)}</Text></View></View>)}</View><View style={styles.integrity}><View style={styles.head}><Ionicons name="shield-checkmark-outline" size={20} color={COLORS.forest}/><Text style={styles.iTitle}>Data Integrity</Text></View><Text style={[styles.verified,{backgroundColor:integrity?.verified?COLORS.greenLight:COLORS.warningLight,color:integrity?.verified?COLORS.forest:"#A16207"}]}>{integrity?.verified?"✓ Verified":"Verification Pending / Failed"}</Text><Row label="Checkpoints" value={integrity?.checkpoints?.length??0}/><Row label="Verification" value={integrity?.verified?"VALID":"NOT VERIFIED"} green={integrity?.verified}/><TouchableOpacity style={styles.btn} onPress={()=>Alert.alert("Integrity Verification",JSON.stringify(integrity,null,2))}><Text style={styles.btnText}>View Verification Details</Text></TouchableOpacity></View></ScrollView></View>
}
const metadataText=m=>!m?"":Object.entries(m).slice(0,2).map(([k,v])=>`${k}: ${typeof v==="object"?JSON.stringify(v):v}`).join(" · ");const formatDate=v=>v?new Date(v).toLocaleString():"—";function Row({label,value,green}){return <View style={styles.row}><Text style={styles.rLabel}>{label}</Text><Text style={[styles.rValue,green&&{color:COLORS.forest}]}>{String(value)}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:COLORS.background},content:{padding:18,paddingBottom:35},err:{color:COLORS.critical,fontFamily:"Inter_500Medium",fontSize:12,marginBottom:10},ship:{fontFamily:"Manrope_800ExtraBold",fontSize:16,color:COLORS.text},product:{fontFamily:"Inter_400Regular",fontSize:12.5,color:COLORS.muted,marginBottom:18},timeline:{marginBottom:20},item:{flexDirection:"row",gap:12},markerCol:{alignItems:"center",width:28},marker:{width:26,height:26,borderRadius:13,backgroundColor:COLORS.blue,alignItems:"center",justifyContent:"center",zIndex:2},completed:{backgroundColor:COLORS.emerald},line:{position:"absolute",top:26,bottom:0,width:2,backgroundColor:COLORS.emerald},tTitle:{fontFamily:"Inter_700Bold",fontSize:13,color:COLORS.text},tSub:{fontFamily:"Inter_400Regular",fontSize:11,color:COLORS.muted,marginTop:2},tTime:{fontFamily:"Inter_400Regular",fontSize:10.5,color:COLORS.muted,marginTop:2},integrity:{backgroundColor:COLORS.white,borderWidth:1,borderColor:COLORS.border,borderRadius:16,padding:16},head:{flexDirection:"row",alignItems:"center",gap:8},iTitle:{fontFamily:"Manrope_700Bold",fontSize:14,color:COLORS.text},verified:{alignSelf:"flex-start",fontFamily:"Inter_700Bold",fontSize:11,paddingHorizontal:10,paddingVertical:4,borderRadius:99,marginVertical:9},row:{flexDirection:"row",justifyContent:"space-between",marginBottom:8},rLabel:{fontFamily:"Inter_400Regular",fontSize:12,color:COLORS.muted},rValue:{fontFamily:"Inter_700Bold",fontSize:11.5,color:COLORS.text},btn:{backgroundColor:COLORS.backgroundBlue,borderWidth:1,borderColor:COLORS.border,borderRadius:11,paddingVertical:11,alignItems:"center",marginTop:5},btnText:{fontFamily:"Inter_700Bold",fontSize:12,color:COLORS.text}})
